/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import InternalFrame.Configuracion.Grupos;
import Metodos.ImagenFondo;
import InternalFrame.Estudiante.BuscarEstudiante;
import InternalFrame.Estudiante.MatriculaEstudiante;
import InternalFrame.Estudiante.MensualidadEstudiante;
import InternalFrame.Estudiante.NuevoEstudiante;
import InternalFrame.Trabajador.UsuarioTrabajador;
import Login.Login;
import Metodos.NewHibernateUtil;
import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

/**
 *
 * @author rommel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

   
    JPopupMenu pm1;
    JPopupMenu pm2;
    JPopupMenu pm3;
    JPopupMenu pm4;
    JPopupMenu pm5;
    JPopupMenu pm6;
    
    private GraphicsEnvironment ge =GraphicsEnvironment.getLocalGraphicsEnvironment();
    private GraphicsDevice gd = null;
    
    public static VentanaPrincipal f ;
    public VentanaPrincipal() {
        initComponents();
        
       
        NewHibernateUtil nhu = new NewHibernateUtil();
        nhu.getSessionFactory("Di-Rommel", "rommel123");
        
        this.setIconImage(ImagenFondo.Icono);
        PopusMenus();
        f = this;
        
    }

   
    public final void PopusMenus(){
        
        pm1 = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Nuevo");
        JMenuItem menuItem2 = new JMenuItem("Matricula");
        JMenuItem menuItem3 = new JMenuItem("Pago Mensualidad");
        JMenuItem menuItem4 = new JMenuItem("Buscar");
        
        menuItem1.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                NuevoMenuIActionPerformed(e);
            }
        });
        menuItem2.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                MatriculaMenuIActionPerformed(e);
            }
        });
        menuItem3.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                PagoMenuIActionPerformed(e);
            }
        });
        menuItem4.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                BuscarMenuIActionPerformed(e);
            }
        });
        
        pm1.add(menuItem1);
        pm1.add(menuItem2);
        pm1.add(menuItem3);
        pm1.add(menuItem4);
        
        
        
        
        
        pm2 = new JPopupMenu();
        
        
        pm3 = new JPopupMenu();
       
        
        pm4 = new JPopupMenu();
        
        
        pm5 = new JPopupMenu();
        
    
    
    
    }
    public void Vista(int opt){
    
    
        switch(opt){
        
            case 1:
                
                Trabajador_NuevoTrabajador1.setVisible(false);
                
                break;
            case 2:
                
                
                break;
            case 3:
                Trabajador_NuevoTrabajador1.setVisible(false);
                
                
                
                break;
            case 4:
                
                
                break;
        
        
        }
        
    
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new ImagenFondo();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jButton2 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jButton4 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        estudiante = new javax.swing.JMenu();
        NuevoMenuI = new javax.swing.JMenuItem();
        MatriculaMenuI = new javax.swing.JMenuItem();
        PagoMenuI = new javax.swing.JMenuItem();
        BuscarMenuI = new javax.swing.JMenuItem();
        notas = new javax.swing.JMenu();
        RegistroMenuI = new javax.swing.JMenuItem();
        Docente_AsignarMaterias = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        ingresos = new javax.swing.JMenu();
        EntradasMenuI = new javax.swing.JMenuItem();
        horario = new javax.swing.JMenu();
        Horarios_HorarioEstudiante1 = new javax.swing.JMenuItem();
        Horarios_HorarioDocente1 = new javax.swing.JMenuItem();
        trabajador = new javax.swing.JMenu();
        Trabajador_NuevoTrabajador1 = new javax.swing.JMenuItem();
        Trabajador_Secretaria1 = new javax.swing.JMenu();
        Trabajador_Secretaria_ActualizarInformacion1 = new javax.swing.JMenuItem();
        Trabajador_Cajero1 = new javax.swing.JMenu();
        Trabajador_Cajero_ActualizarInformacion1 = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        configuracion = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        cession = new javax.swing.JMenu();
        Usuario_CerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana Principal");
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseClicked(evt);
            }
        });

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Estudiante.png"))); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);
        jToolBar1.add(jSeparator3);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Docente.png"))); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator4);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Ingresos.png"))); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton3);
        jToolBar1.add(jSeparator12);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Horario.png"))); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton4);
        jToolBar1.add(jSeparator1);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Trabajador.png"))); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton5);

        estudiante.setText("Estudiante");

        NuevoMenuI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NuevoMenuI.setText("Nuevo");
        NuevoMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoMenuIActionPerformed(evt);
            }
        });
        estudiante.add(NuevoMenuI);

        MatriculaMenuI.setText("Matricula");
        MatriculaMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaMenuIActionPerformed(evt);
            }
        });
        estudiante.add(MatriculaMenuI);

        PagoMenuI.setText("Pago Mensualidad");
        PagoMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagoMenuIActionPerformed(evt);
            }
        });
        estudiante.add(PagoMenuI);

        BuscarMenuI.setText("Buscar");
        BuscarMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMenuIActionPerformed(evt);
            }
        });
        estudiante.add(BuscarMenuI);

        jMenuBar1.add(estudiante);

        notas.setText("Docente");

        RegistroMenuI.setText("Registro de Notas");
        RegistroMenuI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroMenuIActionPerformed(evt);
            }
        });
        notas.add(RegistroMenuI);

        Docente_AsignarMaterias.setText("Asignar materias / Actualizar Infor...");
        Docente_AsignarMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Docente_AsignarMateriasActionPerformed(evt);
            }
        });
        notas.add(Docente_AsignarMaterias);
        notas.add(jSeparator6);

        jMenuBar1.add(notas);

        ingresos.setText("Ingresos");

        EntradasMenuI.setText("Entradas");
        ingresos.add(EntradasMenuI);

        jMenuBar1.add(ingresos);

        horario.setText("Horario");

        Horarios_HorarioEstudiante1.setText("Horarios Estudiantes");
        horario.add(Horarios_HorarioEstudiante1);

        Horarios_HorarioDocente1.setText("Horario Docente");
        horario.add(Horarios_HorarioDocente1);

        jMenuBar1.add(horario);

        trabajador.setText("Trabajador");

        Trabajador_NuevoTrabajador1.setText("Nuevo Trabajador");
        Trabajador_NuevoTrabajador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trabajador_NuevoTrabajador1ActionPerformed(evt);
            }
        });
        trabajador.add(Trabajador_NuevoTrabajador1);

        Trabajador_Secretaria1.setText("Secretaria");

        Trabajador_Secretaria_ActualizarInformacion1.setText("Actualizar Información");
        Trabajador_Secretaria_ActualizarInformacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trabajador_Secretaria_ActualizarInformacion1ActionPerformed(evt);
            }
        });
        Trabajador_Secretaria1.add(Trabajador_Secretaria_ActualizarInformacion1);

        trabajador.add(Trabajador_Secretaria1);

        Trabajador_Cajero1.setText("Cajero");

        Trabajador_Cajero_ActualizarInformacion1.setText("Actualizar Información");
        Trabajador_Cajero_ActualizarInformacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trabajador_Cajero_ActualizarInformacion1ActionPerformed(evt);
            }
        });
        Trabajador_Cajero1.add(Trabajador_Cajero_ActualizarInformacion1);

        trabajador.add(Trabajador_Cajero1);

        jMenuBar1.add(trabajador);

        help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Help.png"))); // NOI18N
        help.setText("Ayuda");
        jMenuBar1.add(help);

        configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Configuration.png"))); // NOI18N
        configuracion.setText("Configuracion");

        jMenuItem7.setText("Gestiones");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        configuracion.add(jMenuItem7);

        jMenuBar1.add(configuracion);

        cession.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/session.png"))); // NOI18N
        cession.setText("Sesión");

        Usuario_CerrarSesion.setText("Cerrar sesión ");
        Usuario_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Usuario_CerrarSesionActionPerformed(evt);
            }
        });
        cession.add(Usuario_CerrarSesion);

        jMenuBar1.add(Box.createHorizontalGlue());
        jMenuBar1.add(configuracion);
        jMenuBar1.add(help);

        jMenuBar1.add(cession);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MatriculaMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaMenuIActionPerformed
        try {
            
            MatriculaEstudiante matricula = new MatriculaEstudiante();
            matricula.setVisible(true);
            jDesktopPane1.add(matricula);
            matricula.setSelected(true);
            matricula.desktop = jDesktopPane1;
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MatriculaMenuIActionPerformed

    
    private void NuevoMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoMenuIActionPerformed
        
        try {
            
            NuevoEstudiante nuevoEstudiante = new NuevoEstudiante();
            nuevoEstudiante.setVisible(true);
            nuevoEstudiante.desktop = jDesktopPane1;
            jDesktopPane1.add(nuevoEstudiante);
            nuevoEstudiante.setSelected(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_NuevoMenuIActionPerformed

    private void BuscarMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMenuIActionPerformed
        try {
            BuscarEstudiante buscarEstudiante = new BuscarEstudiante();
            buscarEstudiante.setVisible(true);
            jDesktopPane1.add(buscarEstudiante);
            buscarEstudiante.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
                
    }//GEN-LAST:event_BuscarMenuIActionPerformed

    private void PagoMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagoMenuIActionPerformed
        try {
            MensualidadEstudiante mensualidad = new MensualidadEstudiante();
            mensualidad.setVisible(true);
            jDesktopPane1.add(mensualidad);
            mensualidad.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PagoMenuIActionPerformed

    private void Docente_AsignarMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Docente_AsignarMateriasActionPerformed
        // TODO add your handling code here:
//        AdministracionDocente a = new AdministracionDocente();
//        a.setVisible(true);
//        jDesktopPane1.add(a);
//        a.setFocusable(true);
    }//GEN-LAST:event_Docente_AsignarMateriasActionPerformed

    private void Trabajador_NuevoTrabajador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trabajador_NuevoTrabajador1ActionPerformed
        try {
            UsuarioTrabajador usuario = new UsuarioTrabajador();
            usuario.setVisible(true);
            jDesktopPane1.add(usuario);
            usuario.setSelected(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Trabajador_NuevoTrabajador1ActionPerformed

    private void Trabajador_Secretaria_ActualizarInformacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trabajador_Secretaria_ActualizarInformacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trabajador_Secretaria_ActualizarInformacion1ActionPerformed

    private void Trabajador_Cajero_ActualizarInformacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trabajador_Cajero_ActualizarInformacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trabajador_Cajero_ActualizarInformacion1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    
//        Cerrar();
    System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void Usuario_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Usuario_CerrarSesionActionPerformed
        
//       Cerrar();
         System.exit(0);
    }//GEN-LAST:event_Usuario_CerrarSesionActionPerformed

    private void RegistroMenuIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroMenuIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistroMenuIActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
        try {
            
            Grupos grupos = new Grupos();
            grupos.setVisible(true);
            jDesktopPane1.add(grupos);
            grupos.setSelected(true);
            
        } catch (PropertyVetoException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jDesktopPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseClicked
       
        
        
    }//GEN-LAST:event_jDesktopPane1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        pm1.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        pm2.show(evt.getComponent(),evt.getX(), evt.getY());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        pm3.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        pm4.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        pm5.show(evt.getComponent(), evt.getX(), evt.getY());
    }//GEN-LAST:event_jButton5MouseClicked

    public void Cerrar(){
    
        int message = JOptionPane.showConfirmDialog(null, "Esta seguro que desea salir de sesión","Salir sesión",
              JOptionPane.YES_NO_OPTION);
    
    if(message != JOptionPane.YES_OPTION){
    
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
    
    }else{
        Login login = new Login();
        login.setVisible(true);
        
        this.dispose();
        System.exit(0);
    }
    
    }
    
    
    public static void getLookAndFeet(){
        System.out.println(new File("").getAbsolutePath());
        NimRODTheme tema = new NimRODTheme(new File("").getAbsolutePath()+"/src/Configuracion/LoginTheme.theme");
        
        NimRODLookAndFeel lookandfeel = new NimRODLookAndFeel();
        NimRODLookAndFeel.setCurrentTheme(tema);
        try {
            UIManager.setLookAndFeel(lookandfeel);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        getLookAndFeet();
                    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

      /* Create and display the form */
           
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuscarMenuI;
    private javax.swing.JMenuItem Docente_AsignarMaterias;
    private javax.swing.JMenuItem EntradasMenuI;
    private javax.swing.JMenuItem Horarios_HorarioDocente1;
    private javax.swing.JMenuItem Horarios_HorarioEstudiante1;
    private javax.swing.JMenuItem MatriculaMenuI;
    private javax.swing.JMenuItem NuevoMenuI;
    private javax.swing.JMenuItem PagoMenuI;
    private javax.swing.JMenuItem RegistroMenuI;
    private javax.swing.JMenu Trabajador_Cajero1;
    private javax.swing.JMenuItem Trabajador_Cajero_ActualizarInformacion1;
    private javax.swing.JMenuItem Trabajador_NuevoTrabajador1;
    private javax.swing.JMenu Trabajador_Secretaria1;
    private javax.swing.JMenuItem Trabajador_Secretaria_ActualizarInformacion1;
    private javax.swing.JMenuItem Usuario_CerrarSesion;
    private javax.swing.JMenu cession;
    private javax.swing.JMenu configuracion;
    private javax.swing.JMenu estudiante;
    private javax.swing.JMenu help;
    private javax.swing.JMenu horario;
    private javax.swing.JMenu ingresos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu notas;
    private javax.swing.JMenu trabajador;
    // End of variables declaration//GEN-END:variables
}
