/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalFrame.Estudiante;

import Metodos.ImagenFondo;
import Clases.Tutor;
import Metodos.Validar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rommel
 */
public class NuevoTutor extends javax.swing.JInternalFrame {

    public NuevoEstudiante nuevo;
    String[] vector = new String[]{ "Seleccionar Opcion", "Madre", "Padre", "Hermano(a)", "Abuelo(a)", "Tio(a)", "Madrina/Padrino" };
    
    Tutor tutor;
    public NuevoTutor() {
        initComponents();
        tutor = new Tutor();
    }

    public int HallarParentesco(String cadena){
    
        for(int i=0;i<vector.length;i++){
        
            if(cadena.equals(vector[i])){
            
                return i;
            
            }
        
        }
    return 0;
    }
    
    public void EditarTutor(){
    
        tutor = nuevo.tutores.get(nuevo.val);
        
        nombre.setText(tutor.getNombre());
        apellido.setText(tutor.getApellido());
        telefono.setText(tutor.getTelefono());
        direccion.setText(tutor.getDireccion());
        parentesco.setSelectedIndex(HallarParentesco(tutor.getParentesco().trim()));
        cedula.setText(tutor.getNumeroDeCedula());
        ocupacion.setText(tutor.getOcupacion());
        
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        telefono = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ocupacion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cedula = new javax.swing.JFormattedTextField();
        guardar = new javax.swing.JButton();
        parentesco = new javax.swing.JComboBox();
        cancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo Tutor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel3.setText("Nombre");

        nombre.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel4.setText("Apellido");

        apellido.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel2.setText("Teléfono");

        telefono.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        direccion.setColumns(20);
        direccion.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        direccion.setLineWrap(true);
        direccion.setRows(5);
        jScrollPane1.setViewportView(direccion);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel6.setText("Dirección");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel5.setText("Parentesco");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel7.setText("Ocupacion");

        ocupacion.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
        jLabel8.setText("Cédula");

        cedula.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Save.png"))); // NOI18N
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        parentesco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccionar Opcion", "Madre", "Padre", "Hermano(a)", "Abuelo(a)", "Tio(a)", "Madrina/Padrino" }));

        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Cancelar.png"))); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(apellido))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6)
                        .addGap(210, 210, 210))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nombre)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(parentesco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        telefono.setFormatterFactory(ImagenFondo.getFormato("####-####"));
        cedula.setFormatterFactory(ImagenFondo.getFormato("###-######-####U"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        nuevo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       
        

        
        Validar validar = new Validar();
        
        
        tutor.setNombre(nombre.getText().trim());
        tutor.setApellido(apellido.getText().trim());
        tutor.setNumeroDeCedula(cedula.getText().trim());
        tutor.setTelefono(telefono.getText().trim());
        tutor.setParentesco(parentesco.getSelectedItem().toString());
        tutor.setDireccion(direccion.getText().trim());
        tutor.setOcupacion(ocupacion.getText().trim());
        
       
        
        
        if(Validacion(tutor)){
        
        
        nuevo.MetodoTutor(tutor);
        nuevo.setVisible(true);
        this.dispose();
        
        }
        
        
        
        
    }//GEN-LAST:event_guardarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        
        nuevo.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_formInternalFrameClosing
    public boolean Vacio(){
    
        if(nombre.getText().trim().equals("") || apellido.getText().trim().equals("") || 
                direccion.getText().equals("") || cedula.getText().trim().equals("--") ||
                telefono.getText().equals("-") || ocupacion.getText().trim().equals("")){
        
         JOptionPane.showMessageDialog(null, "Unos de los campos se encuentra vacio");
        return false;
        }else{
        
           
            return true;
        }
    
    
    }
    public boolean Validacion(Tutor tutor){
    
        Validar validar = new Validar();
        if(Vacio() && validar.ValidarLetras(tutor.getNombre(), "Nombre") && 
                validar.ValidarLetras(tutor.getApellido(), "Apellido") && 
                validar.Cedula(tutor.getNumeroDeCedula()) && 
                validar.ValidarLetras(tutor.getOcupacion(), "Ocupacion")){
        
            if(parentesco.getSelectedIndex()!=0){
            
               tutor.setNombre( validar.ArreglarCadenas(tutor.getNombre()));
               tutor.setApellido(validar.ArreglarCadenas(tutor.getApellido()));
               tutor.setOcupacion(validar.ArreglarCadenas(tutor.getOcupacion()));
                
               try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NuevoTutor.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                return true;
            
            }else{
           
                JOptionPane.showMessageDialog(null, "Debe seleccionar una opcion en el parentesco con el estudiante"
                ,"Error de no seleccionar parentesco",JOptionPane.ERROR_MESSAGE);
                return false;
                
            }
            
        }else{
        
            return false;
        
        }
    
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellido;
    private javax.swing.JButton cancelar;
    private javax.swing.JFormattedTextField cedula;
    private javax.swing.JTextArea direccion;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField ocupacion;
    private javax.swing.JComboBox parentesco;
    private javax.swing.JFormattedTextField telefono;
    // End of variables declaration//GEN-END:variables
}
