package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DocenteMateria generated by hbm2java
 */
public class DocenteMateria  implements java.io.Serializable {


     private Integer idDocenteMateria;
     private Materia materia;
     private Trabajador trabajador;
     private Set horarios = new HashSet(0);

    public DocenteMateria() {
    }

	
    public DocenteMateria(Materia materia, Trabajador trabajador) {
        this.materia = materia;
        this.trabajador = trabajador;
    }
    public DocenteMateria(Materia materia, Trabajador trabajador, Set horarios) {
       this.materia = materia;
       this.trabajador = trabajador;
       this.horarios = horarios;
    }
   
    public Integer getIdDocenteMateria() {
        return this.idDocenteMateria;
    }
    
    public void setIdDocenteMateria(Integer idDocenteMateria) {
        this.idDocenteMateria = idDocenteMateria;
    }
    public Materia getMateria() {
        return this.materia;
    }
    
    public void setMateria(Materia materia) {
        this.materia = materia;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


