package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private Integer idEstudiante;
     private String numeroCarnet;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private Date fechaNacimiento;
     private String lugarDeNacimiento;
     private String genero;
     private int tipoSangre;
     private boolean tipo;
     private boolean estado;
     private Set tutors = new HashSet(0);
     private Set notas = new HashSet(0);
     private Set matriculas = new HashSet(0);

    public Estudiante() {
    }

	
    public Estudiante(String numeroCarnet, String nombre, String apellido, String direccion, String telefono, Date fechaNacimiento, String lugarDeNacimiento, int tipoSangre, boolean tipo, boolean estado) {
        this.numeroCarnet = numeroCarnet;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.telefono = telefono;
        this.fechaNacimiento = fechaNacimiento;
        this.lugarDeNacimiento = lugarDeNacimiento;
        this.tipoSangre = tipoSangre;
        this.tipo = tipo;
        this.estado = estado;
    }
    public Estudiante(String numeroCarnet, String nombre, String apellido, String direccion, String telefono, Date fechaNacimiento, String lugarDeNacimiento, String genero, int tipoSangre, boolean tipo, boolean estado, Set tutors, Set notas, Set matriculas) {
       this.numeroCarnet = numeroCarnet;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fechaNacimiento = fechaNacimiento;
       this.lugarDeNacimiento = lugarDeNacimiento;
       this.genero = genero;
       this.tipoSangre = tipoSangre;
       this.tipo = tipo;
       this.estado = estado;
       this.tutors = tutors;
       this.notas = notas;
       this.matriculas = matriculas;
    }
   
    public Integer getIdEstudiante() {
        return this.idEstudiante;
    }
    
    public void setIdEstudiante(Integer idEstudiante) {
        this.idEstudiante = idEstudiante;
    }
    public String getNumeroCarnet() {
        return this.numeroCarnet;
    }
    
    public void setNumeroCarnet(String numeroCarnet) {
        this.numeroCarnet = numeroCarnet;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getLugarDeNacimiento() {
        return this.lugarDeNacimiento;
    }
    
    public void setLugarDeNacimiento(String lugarDeNacimiento) {
        this.lugarDeNacimiento = lugarDeNacimiento;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public int getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(int tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public boolean isTipo() {
        return this.tipo;
    }
    
    public void setTipo(boolean tipo) {
        this.tipo = tipo;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getTutors() {
        return this.tutors;
    }
    
    public void setTutors(Set tutors) {
        this.tutors = tutors;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


