package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * FacturaMensualidad generated by hbm2java
 */
public class FacturaMensualidad  implements java.io.Serializable {


     private Integer idFacturaMensualidad;
     private Trabajador trabajador;
     private Date fecha;
     private Set pagoMensualidads = new HashSet(0);

    public FacturaMensualidad() {
    }

	
    public FacturaMensualidad(Trabajador trabajador, Date fecha) {
        this.trabajador = trabajador;
        this.fecha = fecha;
    }
    public FacturaMensualidad(Trabajador trabajador, Date fecha, Set pagoMensualidads) {
       this.trabajador = trabajador;
       this.fecha = fecha;
       this.pagoMensualidads = pagoMensualidads;
    }
   
    public Integer getIdFacturaMensualidad() {
        return this.idFacturaMensualidad;
    }
    
    public void setIdFacturaMensualidad(Integer idFacturaMensualidad) {
        this.idFacturaMensualidad = idFacturaMensualidad;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getPagoMensualidads() {
        return this.pagoMensualidads;
    }
    
    public void setPagoMensualidads(Set pagoMensualidads) {
        this.pagoMensualidads = pagoMensualidads;
    }




}


