package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grado generated by hbm2java
 */
public class Grado  implements java.io.Serializable {


     private Integer idGrado;
     private String nombre;
     private Integer nivel;
     private Set matriculaGrados = new HashSet(0);
     private Set grupos = new HashSet(0);

    public Grado() {
    }

    public Grado(String nombre, Integer nivel, Set matriculaGrados, Set grupos) {
       this.nombre = nombre;
       this.nivel = nivel;
       this.matriculaGrados = matriculaGrados;
       this.grupos = grupos;
    }
   
    public Integer getIdGrado() {
        return this.idGrado;
    }
    
    public void setIdGrado(Integer idGrado) {
        this.idGrado = idGrado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public Set getMatriculaGrados() {
        return this.matriculaGrados;
    }
    
    public void setMatriculaGrados(Set matriculaGrados) {
        this.matriculaGrados = matriculaGrados;
    }
    public Set getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Set grupos) {
        this.grupos = grupos;
    }




}


