package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private Grado grado;
     private String nombre;
     private int cupos;
     private Set horarios = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(Grado grado, String nombre, int cupos) {
        this.grado = grado;
        this.nombre = nombre;
        this.cupos = cupos;
    }
    public Grupo(Grado grado, String nombre, int cupos, Set horarios) {
       this.grado = grado;
       this.nombre = nombre;
       this.cupos = cupos;
       this.horarios = horarios;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getCupos() {
        return this.cupos;
    }
    
    public void setCupos(int cupos) {
        this.cupos = cupos;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


