package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1



/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private DocenteMateria docenteMateria;
     private Grupo grupo;
     private int hora;
     private int dia;

    public Horario() {
    }

    public Horario(DocenteMateria docenteMateria, Grupo grupo, int hora, int dia) {
       this.docenteMateria = docenteMateria;
       this.grupo = grupo;
       this.hora = hora;
       this.dia = dia;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public DocenteMateria getDocenteMateria() {
        return this.docenteMateria;
    }
    
    public void setDocenteMateria(DocenteMateria docenteMateria) {
        this.docenteMateria = docenteMateria;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public int getHora() {
        return this.hora;
    }
    
    public void setHora(int hora) {
        this.hora = hora;
    }
    public int getDia() {
        return this.dia;
    }
    
    public void setDia(int dia) {
        this.dia = dia;
    }




}


