package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1



/**
 * MatriculaGrado generated by hbm2java
 */
public class MatriculaGrado  implements java.io.Serializable {


     private int idMatriculaGrado;
     private Grado grado;
     private Matricula matricula;

    public MatriculaGrado() {
    }

    public MatriculaGrado(int idMatriculaGrado, Grado grado, Matricula matricula) {
       this.idMatriculaGrado = idMatriculaGrado;
       this.grado = grado;
       this.matricula = matricula;
    }
   
    public int getIdMatriculaGrado() {
        return this.idMatriculaGrado;
    }
    
    public void setIdMatriculaGrado(int idMatriculaGrado) {
        this.idMatriculaGrado = idMatriculaGrado;
    }
    public Grado getGrado() {
        return this.grado;
    }
    
    public void setGrado(Grado grado) {
        this.grado = grado;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }




}


