package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mensualidad generated by hbm2java
 */
public class Mensualidad  implements java.io.Serializable {


     private Integer idMensualidad;
     private Matricula matricula;
     private Date fecha;
     private boolean estado;
     private Set pagoMensualidads = new HashSet(0);

    public Mensualidad() {
    }

	
    public Mensualidad(Matricula matricula, Date fecha, boolean estado) {
        this.matricula = matricula;
        this.fecha = fecha;
        this.estado = estado;
    }
    public Mensualidad(Matricula matricula, Date fecha, boolean estado, Set pagoMensualidads) {
       this.matricula = matricula;
       this.fecha = fecha;
       this.estado = estado;
       this.pagoMensualidads = pagoMensualidads;
    }
   
    public Integer getIdMensualidad() {
        return this.idMensualidad;
    }
    
    public void setIdMensualidad(Integer idMensualidad) {
        this.idMensualidad = idMensualidad;
    }
    public Matricula getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Matricula matricula) {
        this.matricula = matricula;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getPagoMensualidads() {
        return this.pagoMensualidads;
    }
    
    public void setPagoMensualidads(Set pagoMensualidads) {
        this.pagoMensualidads = pagoMensualidads;
    }




}


