package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Monto generated by hbm2java
 */
public class Monto  implements java.io.Serializable {


     private Integer idMonto;
     private double montoMatricula;
     private double montoMensualidad;
     private double interesMensualidad;
     private Set matriculas = new HashSet(0);

    public Monto() {
    }

	
    public Monto(double montoMatricula, double montoMensualidad, double interesMensualidad) {
        this.montoMatricula = montoMatricula;
        this.montoMensualidad = montoMensualidad;
        this.interesMensualidad = interesMensualidad;
    }
    public Monto(double montoMatricula, double montoMensualidad, double interesMensualidad, Set matriculas) {
       this.montoMatricula = montoMatricula;
       this.montoMensualidad = montoMensualidad;
       this.interesMensualidad = interesMensualidad;
       this.matriculas = matriculas;
    }
   
    public Integer getIdMonto() {
        return this.idMonto;
    }
    
    public void setIdMonto(Integer idMonto) {
        this.idMonto = idMonto;
    }
    public double getMontoMatricula() {
        return this.montoMatricula;
    }
    
    public void setMontoMatricula(double montoMatricula) {
        this.montoMatricula = montoMatricula;
    }
    public double getMontoMensualidad() {
        return this.montoMensualidad;
    }
    
    public void setMontoMensualidad(double montoMensualidad) {
        this.montoMensualidad = montoMensualidad;
    }
    public double getInteresMensualidad() {
        return this.interesMensualidad;
    }
    
    public void setInteresMensualidad(double interesMensualidad) {
        this.interesMensualidad = interesMensualidad;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


