package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String nombre;
     private String descripcion;
     private boolean estado;
     private Set trabajadors = new HashSet(0);

    public Rol() {
    }

	
    public Rol(String nombre, String descripcion, boolean estado) {
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.estado = estado;
    }
    public Rol(String nombre, String descripcion, boolean estado, Set trabajadors) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.trabajadors = trabajadors;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getTrabajadors() {
        return this.trabajadors;
    }
    
    public void setTrabajadors(Set trabajadors) {
        this.trabajadors = trabajadors;
    }




}


