package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private Integer idTrabajador;
     private Rol rol;
     private String nombre;
     private String apellido;
     private String direccion;
     private String numeroDeCedula;
     private String telefono;
     private int tipoSangre;
     private boolean estadoCivil;
     private boolean estado;
     private Set facturaMensualidads = new HashSet(0);
     private Set docenteMaterias = new HashSet(0);
     private Set notas = new HashSet(0);
     private Set matriculas = new HashSet(0);

    public Trabajador() {
    }

	
    public Trabajador(Rol rol, String nombre, String apellido, String direccion, String numeroDeCedula, String telefono, int tipoSangre, boolean estadoCivil, boolean estado) {
        this.rol = rol;
        this.nombre = nombre;
        this.apellido = apellido;
        this.direccion = direccion;
        this.numeroDeCedula = numeroDeCedula;
        this.telefono = telefono;
        this.tipoSangre = tipoSangre;
        this.estadoCivil = estadoCivil;
        this.estado = estado;
    }
    public Trabajador(Rol rol, String nombre, String apellido, String direccion, String numeroDeCedula, String telefono, int tipoSangre, boolean estadoCivil, boolean estado, Set facturaMensualidads, Set docenteMaterias, Set notas, Set matriculas) {
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.numeroDeCedula = numeroDeCedula;
       this.telefono = telefono;
       this.tipoSangre = tipoSangre;
       this.estadoCivil = estadoCivil;
       this.estado = estado;
       this.facturaMensualidads = facturaMensualidads;
       this.docenteMaterias = docenteMaterias;
       this.notas = notas;
       this.matriculas = matriculas;
    }
   
    public Integer getIdTrabajador() {
        return this.idTrabajador;
    }
    
    public void setIdTrabajador(Integer idTrabajador) {
        this.idTrabajador = idTrabajador;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNumeroDeCedula() {
        return this.numeroDeCedula;
    }
    
    public void setNumeroDeCedula(String numeroDeCedula) {
        this.numeroDeCedula = numeroDeCedula;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(int tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public boolean isEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(boolean estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getFacturaMensualidads() {
        return this.facturaMensualidads;
    }
    
    public void setFacturaMensualidads(Set facturaMensualidads) {
        this.facturaMensualidads = facturaMensualidads;
    }
    public Set getDocenteMaterias() {
        return this.docenteMaterias;
    }
    
    public void setDocenteMaterias(Set docenteMaterias) {
        this.docenteMaterias = docenteMaterias;
    }
    public Set getNotas() {
        return this.notas;
    }
    
    public void setNotas(Set notas) {
        this.notas = notas;
    }
    public Set getMatriculas() {
        return this.matriculas;
    }
    
    public void setMatriculas(Set matriculas) {
        this.matriculas = matriculas;
    }




}


