package Clases;
// Generated 10-20-2015 07:14:19 PM by Hibernate Tools 4.3.1



/**
 * Tutor generated by hbm2java
 */
public class Tutor  implements java.io.Serializable {


     private Integer idTutor;
     private Estudiante estudiante;
     private String nombre;
     private String apellido;
     private String direccion;
     private String telefono;
     private String parentesco;
     private String ocupacion;
     private String numeroDeCedula;
     private boolean estado;

    public Tutor() {
    }

    public Tutor(Estudiante estudiante, String nombre, String apellido, String direccion, String telefono, String parentesco, String ocupacion, String numeroDeCedula, boolean estado) {
       this.estudiante = estudiante;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.telefono = telefono;
       this.parentesco = parentesco;
       this.ocupacion = ocupacion;
       this.numeroDeCedula = numeroDeCedula;
       this.estado = estado;
    }
   
    public Integer getIdTutor() {
        return this.idTutor;
    }
    
    public void setIdTutor(Integer idTutor) {
        this.idTutor = idTutor;
    }
    public Estudiante getEstudiante() {
        return this.estudiante;
    }
    
    public void setEstudiante(Estudiante estudiante) {
        this.estudiante = estudiante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getParentesco() {
        return this.parentesco;
    }
    
    public void setParentesco(String parentesco) {
        this.parentesco = parentesco;
    }
    public String getOcupacion() {
        return this.ocupacion;
    }
    
    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public String getNumeroDeCedula() {
        return this.numeroDeCedula;
    }
    
    public void setNumeroDeCedula(String numeroDeCedula) {
        this.numeroDeCedula = numeroDeCedula;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }




}


